### ISSUE TITLE
Continous Crash

### ISSUE THREAD

**Issue by dcornacho** [tbwfdu/fetch#1]
Hello,

following your message in Slack, I've started yesterday to try Fetch.

On my Windows 11 pc, it is crashing very often. I've tried many times to get a report of the apps I am deploying (which works), but when i try to delive an app update (for VLC), the app crashes and quits at the beginning of the step "Uploading Custom Install/Uninstall scripts".

I've also tried to upload another app (Spotify) from the "Search aplication" page. Here the app doesn't crashes, but the upload hangs at the same "Updating Custom Install/uninstall scripts". It stays there, with the circle rotation going on, but never ends.

Please let me know if youn need any other information.

Davide Corna

**Comment by tbwfdu** [comment]
@dcornacho  - Are you able to enable Verbose Logs and share them with me? 

Also, check that you dont have the report open already in another app (eg. the report open in Excel) as it cannot parse the file when its already open.

**Comment by auanasgheps** [comment]
I am seeing some instability too.
I was able to upload an application on the second attempt (first attempt crashed) but it also crashes every time I try to get Application Updates in my environment. 

I've enabled verbose logging but it doesn't show much 
[log20240904.txt](https://github.com/user-attachments/files/16866008/log20240904.txt)

**Comment by dcornacho** [comment]
[log20240904.txt](https://github.com/user-attachments/files/16870136/log20240904.txt)
https://chostfeld-my.sharepoint.com/:v:/g/personal/dcorna_ostfeld_com/EW4E3YcNQ4xDnVZKAGwGJ3EBy_O0Jry18gb9ii00P5MMYA?e=y7aB7E

I am sending verbose logs and a video of what I was trying to do.

Thanks.

**Comment by dcornacho** [comment]
I've noticed that the Appication Event Viewer reports an error about, which says the module generating the error is C:\Program Files\Fetch\Microsoft.ui.xaml.dll

**Comment by TroyLambert-CoP** [comment]
I can confirm. getting crashes as well, on 2 different systems. The offending module is Microsoft.ui.xaml.dll, version 3.1.5.0.


![Screenshot 2024-09-06 134159](https://github.com/user-attachments/assets/2e33b92b-cd8a-43df-9022-b5fb036b251b)

**Comment by dcornacho** [comment]
version  3.1.5.0 for me too, actually

**Comment by tbwfdu** [comment]
I've added a pre-release version. Please try out this version and report back if the issues are resolved.

**Comment by dcornacho** [comment]
Hello,

thanks. I am not having the same issue anymore. However, I am now getting an error in the UI while trying to upload any application (I've tried 3 different apps). I am sending the logs attached .
[log20240916.txt](https://github.com/user-attachments/files/17011734/log20240916.txt)

**Comment by tbwfdu** [comment]
Currently, Fetch only supports Customer OG types. I can see from your logs that the response from the API only returns "container" types. There has been other requests to support all OG types but at the moment it is only looking for Customer types and hence the error.

Essentially its failing as it cannot upload as it doesn't have the correct values for the OG & UUID.

**Comment by dcornacho** [comment]
Oh ok, thanks. This is a test environment in which we didn't configure anything at Customer OG, leaving it blank for more flexibility in testing.
"only supports Customer OG types" means that I shoud just create the Oauth client at the Customer OG level, or do apps need to be uploaded at Customer OG level too?

**Comment by auanasgheps** [comment]
The beta/pre-release version does not crash anymore when fetching updates! Thank you

**Comment by TroyLambert-CoP** [comment]
Much better performance with 0.4.0 Beta. no crashing.
