### ISSUE TITLE
How do we suggest new applications to add to the Fetch library?

### ISSUE THREAD

**Issue by TroyLambert-CoP** [tbwfdu/fetch#4]
Is there a mechanism to add suggestions for installers to add to the Fetch library, such as FileZilla?

**Comment by auanasgheps** [comment]
I'm sure they're pulled from winget... and no, Filezilla is not in the winget repository.
It must be for some weird reasons, since it's a popular piece of software.

EDIT: it's for a very stupid reason: https://github.com/microsoft/winget-pkgs/issues/173955#issuecomment-2356612837

**Comment by tbwfdu** [comment]
@auanasgheps is correct. Applications and their installers come directly from the Winget manifests repository. 

I have considered the idea of having user submitted applications but that introduces a lot of challenges around vetting and validating submissions.

**Comment by TroyLambert-CoP** [comment]
Thank you
