### ISSUE TITLE
Install timeout is incorrectly set to 0

### ISSUE THREAD

**Issue by auanasgheps** [tbwfdu/fetch#5]
For each app uploaded by Fetch, the install timeout is set to 0.
This leads to installation errors.

I recommend setting this to 10/15 minutes.

![immagine](https://github.com/user-attachments/assets/bc4f103c-2194-45a2-8384-ba60d53b970d)

**Comment by tbwfdu** [comment]
I have made an adjustment to this setting and will be available in the next release. 

There a lot of changes in the next version so I’ve been holding off building a new installer. I expect I’ll be able to put out a new installer next week.

**Comment by tbwfdu** [comment]
This has been resolved in the latest release (v0.5.0)
