### ISSUE TITLE
App crash with version 0.6.0 and Microsoft.ui.xaml.dll version 3.1.5.0

### ISSUE THREAD

**Issue by TroyLambert-CoP** [tbwfdu/fetch#9]
After upgrading Fetch to 0.6.0, I am getting application errors when trying to launch Fetch, both from an upgrade from 0.5.0, and on new installs. I checked the Event log, and found these entries:
![Fetch 0 6 0 Errors](https://github.com/user-attachments/assets/f5d2d1bb-7cc9-4ac5-aeab-fe5ab339de5b)

**Comment by tbwfdu** [comment]
Is there anything more specific on the logs? I think that we have seen this error before, and its related to a specific process trying to access something in the UI that hasn't rendered yet. If it managed to capture the last thing it attempted  in the logs it will give me a starting place to look.

**Comment by tbwfdu** [comment]
I was able to reproduce this on the x64 build as well. The issue is with the installer itself.

I have uploaded a new installer to the releases page that fixes this. There was a file missing from the msi.
